# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=2500)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2)),
                ('state_of_task', models.IntegerField(choices=[(1, 'Todo'), (2, 'Doing'), (3, 'Done')])),
                ('due_date', models.DateField()),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
